apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: default
data:
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_TOPIC: "user-activity-logs"
  KAFKA_CONSUMER_GROUP: "user-activity-consumer-group"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
stringData:
  connection-string: "mongodb://admin:password@mongodb-service:27017/eyego?authSource=admin"
